"""Safe, deterministic image discovery, deduplication, and output processing."""

from __future__ import annotations

import csv
import hashlib
import logging
import secrets
import shutil
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Final, Iterable

from PIL import Image, ImageOps
from pillow_heif import register_heif_opener

SUPPORTED_EXTENSIONS: Final[frozenset[str]] = frozenset(
    {".jpg", ".jpeg", ".png", ".bmp", ".heic", ".heif"}
)
HEIF_EXTENSIONS: Final[frozenset[str]] = frozenset({".heic", ".heif"})
HASH_CHUNK_SIZE: Final[int] = 1024 * 1024
LOGGER = logging.getLogger(__name__)


class SafetyError(RuntimeError):
    """Raised when a requested operation could affect source data or existing output."""


@dataclass(frozen=True)
class PreparationConfig:
    """Immutable settings for one preparation run.

    Attributes:
        source: Root directory containing the authoritative photo library.
        output: Root directory that will contain ``images`` and ``reports``.
        overwrite_output: Whether existing utility-created output may be rebuilt.
        jpeg_quality: JPEG encoding quality used only for HEIC/HEIF files.
        max_files: Maximum supported images to process, or ``None`` for all.
        randomize_order: Whether to securely shuffle retained image output order.
        dry_run: Whether to produce reports without modifying output images.
    """

    source: Path
    output: Path
    overwrite_output: bool = False
    jpeg_quality: int = 92
    max_files: int | None = None
    randomize_order: bool = False
    dry_run: bool = False


@dataclass(frozen=True)
class ErrorRecord:
    """One recoverable failure encountered while processing a source file."""

    source_path: Path
    operation: str
    exception_type: str
    message: str


@dataclass(frozen=True)
class ManifestRecord:
    """Traceability record for one successful or planned output image."""

    output_filename: str
    source_path: Path
    source_filename: str
    source_extension: str
    sha256: str
    source_bytes: int
    output_bytes: int | None
    action: str
    status: str


@dataclass(frozen=True)
class DuplicateRecord:
    """Record linking an exact duplicate to its retained source."""

    duplicate_path: Path
    retained_path: Path
    sha256: str
    size: int


@dataclass
class PreparationResult:
    """Counters and report records generated by a preparation run."""

    source: Path
    output: Path
    dry_run: bool
    max_files: int | None = None
    candidates_discovered: int = 0
    candidates: int = 0
    unique_images: int = 0
    images_written: int = 0
    duplicates_skipped: int = 0
    conversions_completed: int = 0
    unchanged_files_copied: int = 0
    output_bytes: int = 0
    elapsed_seconds: float = 0.0
    errors: list[ErrorRecord] = field(default_factory=list)
    manifest: list[ManifestRecord] = field(default_factory=list)
    duplicates: list[DuplicateRecord] = field(default_factory=list)

    def summary_text(self) -> str:
        """Return the human-readable summary written at the end of a run."""
        completion = "dry run completed" if self.dry_run else "run completed normally"
        lines = [
            "AGPTEK media preparation summary",
            f"Status: {completion}",
            f"Source: {self.source}",
            f"Output: {self.output}",
            f"Candidate images discovered: {self.candidates_discovered}",
            f"Candidate images selected: {self.candidates}",
            f"Unique images: {self.unique_images}",
            f"Images written: {self.images_written}",
            f"Exact duplicates skipped: {self.duplicates_skipped}",
            f"HEIC/HEIF conversions completed: {self.conversions_completed}",
            f"Unchanged files copied: {self.unchanged_files_copied}",
            f"Errors: {len(self.errors)}",
            f"Output size: {self.output_bytes} bytes",
            f"Elapsed time: {self.elapsed_seconds:.2f} seconds",
        ]
        if self.max_files is not None:
            lines.append(f"Processing limit: first {self.max_files} candidate images")
        if self.dry_run:
            lines.append("No output images were created, replaced, or deleted.")
        return "\n".join(lines) + "\n"


def prepare_library(config: PreparationConfig) -> PreparationResult:
    """Prepare a flat, deduplicated image directory while preserving the source tree.

    The source is only ever opened for reading. Per-file failures are recorded in
    ``errors.csv`` and do not prevent remaining files from being processed.
    """
    started_at = time.monotonic()
    source, output = _validate_config(config)
    images_dir = output / "images"
    reports_dir = output / "reports"
    _validate_existing_output(images_dir, config.overwrite_output)
    result = PreparationResult(
        source=source, output=output, dry_run=config.dry_run, max_files=config.max_files
    )

    discovered_candidates = list(_discover_candidates(source, output))
    result.candidates_discovered = len(discovered_candidates)
    candidates = discovered_candidates[: config.max_files]
    result.candidates = len(candidates)
    LOGGER.info(
        "Discovered %d candidate image files; selected %d for this run.",
        result.candidates_discovered,
        result.candidates,
    )

    retained: list[tuple[Path, str, int]] = []
    hashes: dict[str, Path] = {}
    for index, candidate in enumerate(candidates, start=1):
        try:
            digest, size = _hash_file(candidate)
        except OSError as error:
            _record_error(result, candidate, "hash", error)
            continue

        retained_path = hashes.get(digest)
        if retained_path is not None:
            result.duplicates.append(DuplicateRecord(candidate, retained_path, digest, size))
            result.duplicates_skipped += 1
            LOGGER.info("[%d/%d] duplicate skipped: %s", index, result.candidates, candidate)
            continue
        hashes[digest] = candidate
        retained.append((candidate, digest, size))
        LOGGER.info("[%d/%d] queued: %s", index, result.candidates, candidate)

    result.unique_images = len(retained)
    if config.randomize_order:
        secrets.SystemRandom().shuffle(retained)
        LOGGER.info("Securely randomized the output order of %d unique images.", len(retained))
    _prepare_output_directories(images_dir, reports_dir, config)
    file_handler = _configure_file_logging(reports_dir)
    try:
        for sequence, (candidate, digest, source_size) in enumerate(retained, start=1):
            _process_retained_file(
                candidate, digest, source_size, sequence, images_dir, config, result
            )

        result.elapsed_seconds = time.monotonic() - started_at
        _write_reports(reports_dir, result)
    finally:
        LOGGER.removeHandler(file_handler)
        file_handler.close()
    return result


def _validate_config(config: PreparationConfig) -> tuple[Path, Path]:
    """Validate paths and option values before any output changes occur."""
    if not 1 <= config.jpeg_quality <= 100:
        raise ValueError("jpeg_quality must be between 1 and 100")
    if config.max_files is not None and config.max_files < 1:
        raise ValueError("max_files must be a positive integer or None")
    source = config.source.expanduser().resolve(strict=False)
    if not source.is_dir():
        raise SafetyError(f"Source directory does not exist or is not a directory: {source}")
    output = config.output.expanduser().resolve(strict=False)
    if output == source:
        raise SafetyError("Output directory must not be the same as the source directory.")
    if source.is_relative_to(output):
        raise SafetyError("Output directory must not be a parent of the source directory.")
    return source, output


def _validate_existing_output(images_dir: Path, overwrite_output: bool) -> None:
    """Refuse a non-empty image output folder unless explicit consent was supplied."""
    if images_dir.exists() and not images_dir.is_dir():
        raise SafetyError(f"Output images path is not a directory: {images_dir}")
    if images_dir.is_dir() and any(images_dir.iterdir()) and not overwrite_output:
        raise SafetyError(
            f"Output images folder is non-empty: {images_dir}. "
            "Use --overwrite-output to rebuild it."
        )


def _discover_candidates(source: Path, output: Path) -> Iterable[Path]:
    """Yield supported source files in a stable, case-insensitive path order."""
    candidates: list[Path] = []
    for path in source.rglob("*"):
        if _is_in_output_tree(path, output):
            continue
        if path.is_file() and path.suffix.lower() in SUPPORTED_EXTENSIONS:
            candidates.append(path)
    return iter(sorted(candidates, key=lambda item: str(item).casefold()))


def _is_in_output_tree(path: Path, output: Path) -> bool:
    """Return whether ``path`` is in an output tree nested in the source."""
    try:
        path.relative_to(output)
    except ValueError:
        return False
    return True


def _hash_file(path: Path) -> tuple[str, int]:
    """Return a streaming SHA-256 digest and source byte count."""
    digest = hashlib.sha256()
    size = 0
    with path.open("rb") as source_file:
        for chunk in iter(lambda: source_file.read(HASH_CHUNK_SIZE), b""):
            digest.update(chunk)
            size += len(chunk)
    return digest.hexdigest(), size


def _prepare_output_directories(
    images_dir: Path, reports_dir: Path, config: PreparationConfig
) -> None:
    """Safely initialize output locations after validation and source scanning."""
    if config.dry_run:
        reports_dir.mkdir(parents=True, exist_ok=True)
        return
    if config.overwrite_output:
        _clear_output_directory(images_dir)
        _clear_output_directory(reports_dir)
    images_dir.mkdir(parents=True, exist_ok=True)
    reports_dir.mkdir(parents=True, exist_ok=True)


def _clear_output_directory(directory: Path) -> None:
    """Remove a verified utility-owned output child directory, if it exists."""
    if directory.exists():
        if not directory.is_dir():
            raise SafetyError(f"Expected output directory but found a file: {directory}")
        shutil.rmtree(directory)


def _process_retained_file(
    source_path: Path,
    digest: str,
    source_size: int,
    sequence: int,
    images_dir: Path,
    config: PreparationConfig,
    result: PreparationResult,
) -> None:
    """Copy or convert one unique source, recording an error without stopping the run."""
    extension = source_path.suffix.lower()
    converted = extension in HEIF_EXTENSIONS
    output_extension = ".jpg" if converted else extension
    output_filename = f"{sequence:06d}{output_extension}"
    output_path = images_dir / output_filename
    temporary_path = images_dir / f".{output_filename}.tmp"
    action = "converted" if converted else "copied"
    try:
        if config.dry_run:
            _validate_readable_image(source_path, converted)
            result.manifest.append(
                ManifestRecord(
                    output_filename, source_path, source_path.name, extension, digest,
                    source_size, None, f"would_{action}", "planned"
                )
            )
            return
        if converted:
            _convert_heif(source_path, temporary_path, config.jpeg_quality)
        else:
            _validate_readable_image(source_path, False)
            shutil.copy2(source_path, temporary_path)
        temporary_path.replace(output_path)
        output_size = output_path.stat().st_size
    except Exception as error:  # Individual image decoders may raise library-specific errors.
        if temporary_path.exists():
            temporary_path.unlink()
        _record_error(result, source_path, action, error)
        return

    result.images_written += 1
    result.output_bytes += output_size
    if converted:
        result.conversions_completed += 1
    else:
        result.unchanged_files_copied += 1
    result.manifest.append(
        ManifestRecord(
            output_filename, source_path, source_path.name, extension, digest, source_size,
            output_size, action, "written"
        )
    )
    LOGGER.info("Wrote %s (%d unique images completed).", output_filename, result.images_written)


def _validate_readable_image(path: Path, is_heif: bool) -> None:
    """Decode an image enough to identify corrupt ordinary inputs before copying."""
    if is_heif:
        register_heif_opener()
    with Image.open(path) as image:
        image.verify()


def _convert_heif(source_path: Path, output_path: Path, quality: int) -> None:
    """Convert HEIC/HEIF to orientation-correct RGB JPEG."""
    register_heif_opener()
    with Image.open(source_path) as image:
        _restore_heif_orientation_metadata(image)
        oriented = ImageOps.exif_transpose(image)
        if oriented.mode != "RGB":
            oriented = oriented.convert("RGB")
        oriented.save(output_path, format="JPEG", quality=quality, optimize=True)


def _restore_heif_orientation_metadata(image: Image.Image) -> None:
    """Expose HEIF's original orientation to Pillow before transposing it.

    ``pillow-heif`` preserves the container orientation in
    ``original_orientation`` while presenting a normalized EXIF orientation.  A
    conversion needs the original value so the JPEG pixel data is oriented for
    viewers that do not interpret HEIF metadata.
    """
    original_orientation = image.info.get("original_orientation")
    current_orientation = image.getexif().get(274, 1)
    if isinstance(original_orientation, int) and current_orientation == 1:
        image.getexif()[274] = original_orientation


def _record_error(
    result: PreparationResult, source_path: Path, operation: str, error: Exception
) -> None:
    """Store and log a recoverable per-file error."""
    record = ErrorRecord(source_path, operation, type(error).__name__, str(error))
    result.errors.append(record)
    LOGGER.error("%s failed for %s: %s", operation, source_path, error)


def _configure_file_logging(reports_dir: Path) -> logging.FileHandler:
    """Attach a per-run diagnostic log in the reports directory."""
    handler = logging.FileHandler(reports_dir / "processing.log", encoding="utf-8")
    handler.setFormatter(logging.Formatter("%(asctime)s %(levelname)s %(message)s"))
    LOGGER.addHandler(handler)
    LOGGER.setLevel(logging.INFO)
    return handler


def _write_reports(reports_dir: Path, result: PreparationResult) -> None:
    """Write all CSV and text reports for a completed or dry run."""
    _write_csv(
        reports_dir / "manifest.csv",
        [
            "output_filename", "source_path", "source_filename", "source_extension", "sha256",
            "source_bytes", "output_bytes", "action", "status",
        ],
        (
            (
                item.output_filename, str(item.source_path), item.source_filename,
                item.source_extension, item.sha256, item.source_bytes,
                "" if item.output_bytes is None else item.output_bytes, item.action, item.status,
            )
            for item in result.manifest
        ),
    )
    _write_csv(
        reports_dir / "duplicates.csv",
        ["duplicate_source_path", "retained_source_path", "sha256", "size"],
        ((str(item.duplicate_path), str(item.retained_path), item.sha256, item.size) for item in result.duplicates),
    )
    _write_csv(
        reports_dir / "errors.csv",
        ["source_path", "operation", "exception_type", "message"],
        ((str(item.source_path), item.operation, item.exception_type, item.message) for item in result.errors),
    )
    (reports_dir / "summary.txt").write_text(result.summary_text(), encoding="utf-8")


def _write_csv(path: Path, headers: list[str], rows: Iterable[tuple[object, ...]]) -> None:
    """Write a UTF-8 CSV file with a deterministic header row."""
    with path.open("w", newline="", encoding="utf-8") as report_file:
        writer = csv.writer(report_file)
        writer.writerow(headers)
        writer.writerows(rows)
